# Generated by Django 5.1.2 on 2024-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_admin_certification_project_skill_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
