# Generated by Django 5.1.4 on 2024-12-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_about_image_alter_education_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
