# Generated by Django 5.1.2 on 2024-11-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='about/')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('story', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
