# Generated by Django 5.1.2 on 2024-11-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_about_delete_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
